### ISSUE TITLE
Issue with hands on lab guide - launchapp.sh missing

### ISSUE THREAD

**Issue by raekins** [oracle-devrel/redbull-analytics-hol#31]
https://github.com/oracle-devrel/redbull-analytics-hol/tree/main/beginners#beginners-hands-on-lab

In Starting The Web Application it reads:

cd /home/opc/redbull-analytics-hol/beginners/web
 ./launchapp.sh start

However is launchapp.sh is missing, for example

(redbullenv)  cd /home/opc/redbull-analytics-hol/beginners/web
(redbullenv)  ./launchapp.sh start
bash: ./launchapp.sh: No such file or directory

**Comment by ttscoff** [comment]
Docs have been updated to reflect that the `cd` command was not needed. Sorry for the inconvenience.
